spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortenerdb?useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: 1911
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jackson:
    time-zone: America/Sao_Paulo

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, loggers, env
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Encurtador de URLs
    description: Serviço para encurtar URLs
    version: 1.0.0
    author: Guilherme Brito Souza Santos
    email: guilhermereal1911@gmail.com
    github: https://github.com/guidev1911
  environment:
    name: produção
    region: sa-east-1
  database:
    type: MySQL
    version: 8.0.40

