spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortenerdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 1911
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    time-zone: America/Sao_Paulo

server:
  port: 8080
